name: CI Pipeline
on: [push]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4.0.0
        - name: Set up JDK 11
          uses: actions/setup-java@v3
          with:
              java-version: '11'
              distribution: 'temurin'

        - name: Build with Gradle
          run: |
              chmod +x gradlew
              ./gradlew clean :service-a:build
              
    deploy:
        - name: deploy with docker
          run: |
              docker run -d -p 8081:8080 -e spring.profiles.active=prod -e serviceb.url=http://<HOST_IP>:8082 -e servicec.url=http://<HOST_IP>:8083 narramadan/spring-multi-module-service-service-a

    
        
